version: "3.6"

services:
  app:
    build:
      context: . 
      dockerfile: docker/deploy/Dockerfile
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 3000:3000

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: maindatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
  
